name: "OpenInfra Mexico"
bio: "Open Infrastructure CDMX User Group focused on community development across Mexico."
avatar: images/OpenInfra-UserGroup-Black.svg
social:
  github: opensource-latinamerica
  twitter: OpenInfraCDMX
  email: hello@openinfra.mx
  #website: https://openinfra.mx
  youtube: UCpB__-WAEyHdvKAK0Y15akQ
  rss: "" # Remove RSS
