paginate: 10
paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
enableGitInfo: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

IsMultiLingual: true
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

security:
  funcs:
    getenv: ['^HUGO_', '^CI$', 'PWD']
