---
main: 
  - name: Contact
    identifier: contact
    weight: 100
    url: contact
    params:
      icon: '<i class="fas fa-fw fa-info-circle"></i>'
  - name: Authors
    identifier: authors
    weight: 3
    url: authors
    params:
      icon: '<i class="fas fa-fw fa-heart"></i>'
---
